Controllers/ConteneurController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SopalS.Models.ConteneurModel;
using SopalS.Models;
using Microsoft.EntityFrameworkCore;
using SopalS.Data;
//using System.Data.Entity;
using Microsoft.AspNetCore.Http.HttpResults;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//using System.Data.Entity;
using System.Data.SqlTypes;

namespace SopalS.Controllers
{
    public class ConteneurController : Controller

    {

        private readonly DataContext _dataContext;

        public ConteneurController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        public async Task<IActionResult> Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add([FromBody] AddConteneurviewmodel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Ajouter le nouveau conteneur à votre base de données
                    //entite.dde =null
                    var conteneurtoadd = new Conteneur()
                    {
                        Ref = model.Ref,
                        CodeBarres = model.CodeBarres,
                        EmplacementId = model.EmplacementId,
                        DateMiseEnService = model.DateMiseEnService,
                        PeriodiciteEtalonnage = model.PeriodiciteEtalonnage,
                        DateDernierEtalonnage = model.DateDernierEtalonnage,
                        DernierPoids = model.DernierPoids,
                        Unite = model.Unite,
                        UserCreate = model.UserCreate,
                        UserUpdate = model.UserUpdate,
                        DateCreate = model.DateCreate,
                        DateUpdate = model.DateUpdate
                    };

                    _dataContext.Conteneur.Add(conteneurtoadd);
                    // add function that adds mds+durre to dde 
                    await _dataContext.SaveChangesAsync();

                    // Rediriger vers l'Index après l'ajout
                    return Ok();
                }
                catch (DbUpdateException ex)
                {
                    // Capturer les détails de l'exception interne
                    var errorMessage = ex.InnerException?.Message ?? ex.Message;
                    // Logger l'erreur (vous pouvez utiliser un système de logging approprié)
                    Console.WriteLine(errorMessage);
                    // Retourner une réponse avec un message d'erreur
                    return BadRequest(new { message = errorMessage });
                }
            }

            // Si le modèle n'est pas valide, retourner une réponse BadRequest avec les erreurs du modèle
            return BadRequest(ModelState);
        }
        public async Task<IActionResult> GetEmplacements()
        {
            var emplacements = await _dataContext.Emplacement
                .Select(e => new { e.Codeemp, e.libele })
                .ToListAsync();
            return Json(emplacements);
        }



        public IActionResult Index()
        {
            IEnumerable<Conteneur> objUtilisateurList = _dataContext.Conteneur.ToList();
            return View(objUtilisateurList);
        }
        
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var conteneur = await _dataContext.Conteneur.FindAsync(id);
            if (conteneur == null)
            {
                return NotFound();
            }

            _dataContext.Conteneur.Remove(conteneur);
            await _dataContext.SaveChangesAsync();

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] Conteneur conteneur)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _dataContext.Conteneur.Add(conteneur);
                    await _dataContext.SaveChangesAsync();
                    return Ok();
                }
                catch (DbUpdateException ex)
                {
                
                    Console.WriteLine(ex.InnerException?.Message ?? ex.Message);
                    return BadRequest(new { message = ex.InnerException?.Message ?? ex.Message });
                }
            }
            else
            {
               
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }

            return BadRequest(ModelState);
        }




        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var customer = await _dataContext.Conteneur.FirstOrDefaultAsync(x => x.Ref == id);

            if (customer != null)
            {
                var viewModel = new Conteneur()
                {
                    Ref = customer.Ref,
                    CodeBarres = customer.CodeBarres,
                    EmplacementId = customer.EmplacementId,
                    DateMiseEnService = customer.DateMiseEnService,
                    PeriodiciteEtalonnage = customer.PeriodiciteEtalonnage,
                    DateDernierEtalonnage = customer.DateDernierEtalonnage,
                    DernierPoids = customer.DernierPoids,
                    Unite = customer.Unite,
                    UserCreate = customer.UserCreate,
                    UserUpdate = customer.UserUpdate,
                    DateCreate = customer.DateCreate,
                    DateUpdate = customer.DateUpdate
                };
                return await Task.Run(() => View("Update", viewModel));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(Conteneur model)
        {
            var customer = await _dataContext.Conteneur.FindAsync(model.Ref);
            
            if (customer != null)
            {
                
                customer.CodeBarres = model.CodeBarres;
                customer.EmplacementId = model.EmplacementId;
                customer.DateMiseEnService = model.DateMiseEnService;
                customer.PeriodiciteEtalonnage = model.PeriodiciteEtalonnage;
                customer.DateDernierEtalonnage = model.DateDernierEtalonnage;
                customer.DernierPoids = model.DernierPoids;
                customer.Unite = model.Unite;
                customer.UserCreate = model.UserCreate;
                customer.UserUpdate = model.UserUpdate;
                customer.DateCreate = model.DateCreate;
                customer.DateUpdate = model.DateUpdate;



                await _dataContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }









        // GET: ConteneurController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int? id)


        {
            if (id != null)
            {
                NotFound();
            }

            var product = _dataContext.Conteneur.Find(id);
            return View(product);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Conteneur model)
        {
            var employee = await _dataContext.Conteneur.FindAsync(model.Ref);
            if (employee != null)
            {
                _dataContext.Conteneur.Remove(employee);

                await _dataContext.SaveChangesAsync();
                //return RedirectToAction("Index");
            }
            return RedirectToAction(nameof(Index));
        }

    }

}

Controllers/listeConteneurEchuController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SopalS.Data;
using SopalS.Models.ConteneurModel;
//using System.Data.Entity;

using Microsoft.EntityFrameworkCore;


using System.Collections.Generic;
using System.Threading.Tasks;
using System.Data.Entity.Infrastructure;
//using System.Data.Entity;

namespace SopalS.Controllers
{
    public class listeConteneurEchuController : Controller
    {
        private readonly DataContext _dataContext;

        public listeConteneurEchuController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        // GET: listeConteneurEchuController
        public async Task<IActionResult> Index()
        {
            List<ConteneurViewModel> conteneurs = await _dataContext.Conteneurs.ToListAsync();
            return View(conteneurs);
        }
        [HttpGet]
        public async Task<IActionResult> List(int id)
        {
            var histoEtalonnages = await _dataContext.HistoEtalonnages
                .Where(h => h.Ref == id)
                .ToListAsync();

            return View(histoEtalonnages);
        }
        //public IActionResult Add()
        //{
        //    return View();
        //}
        public async Task<IActionResult> Details(int id)
        {
            var histoEtalonnages = await _dataContext.HistoEtalonnages
                .Where(h => h.Ref == id)
                .ToListAsync();

            if (histoEtalonnages == null)
            {
                return NotFound();
            }

            return View(histoEtalonnages);
        }
        public IActionResult Add(int id)
        {
            var histoEtalonnage = new HistoEtalonnage
            {
                Ref = id,
                Date = DateTime.Now // Initialisation de la date à la date actuelle par exemple
            };

            return View(histoEtalonnage);
        }
        [HttpPost]
        public IActionResult Add(HistoEtalonnage histoEtalonnage)
        {
            if (ModelState.IsValid)
            {
                _dataContext.HistoEtalonnages.Add(histoEtalonnage);
                _dataContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(histoEtalonnage);
        }
        [HttpPost]
        public async Task<IActionResult> GetList()
        {
            var conteneurs = await _dataContext.Conteneurs
                .Select(c => new
                {
                    c.Ref,
                    c.CodeBarres,
                    c.DateMiseEnService,
                    c.PeriodiciteEtalonnage,
                    c.DateDernierEtalonnage,
                    c.DernierPoids,
                    c.Unite,
                    c.UserCreate,
                    c.DateCreate,
                    c.UserUpdate,
                    c.DateUpdate,
                    c.EmplacementId,
                    c.DateProchainEtalonnage,
                    Action = ""
                }).ToListAsync();

            return Json(new { data = conteneurs });
        }


        //[HttpPost]
        //public async Task<IActionResult> Add(HistoEtalonnage histoEtalonnage)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _dataContext.HistoEtalonnages.Add(histoEtalonnage);
        //        await _dataContext.SaveChangesAsync();
        //        return RedirectToAction("Details", new { id = histoEtalonnage.Ref });
        //    }

        //    // Si le modèle n'est pas valide, renvoyer la vue avec les erreurs
        //    return View(histoEtalonnage);
        //}
        // POST: HistoEtalonnage/Add
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Add(HistoEtalonnage histoEtalonnage)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        // Optionally set the Date property to current date if not provided
        //        if (histoEtalonnage.Date == default(DateTime))
        //        {
        //            histoEtalonnage.Date = DateTime.Now;
        //        }

        //        _dataContext.HistoEtalonnages.Add(histoEtalonnage);
        //        await _dataContext.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    return View(histoEtalonnage);
        //}

        //[HttpPost]
        //public async Task<IActionResult> List(HistoEtalonnage histoEtalonnage)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _dataContext.Update(histoEtalonnage);
        //        await _dataContext.SaveChangesAsync();
        //        return RedirectToAction(nameof(List), new { id = histoEtalonnage.Ref });
        //    }
        //    return View(histoEtalonnage);
        //}

        // GET: listeConteneurEchuController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: listeConteneurEchuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: listeConteneurEchuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: listeConteneurEchuController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: listeConteneurEchuController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: listeConteneurEchuController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: listeConteneurEchuController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/listeConteneurEchu/Add.cshtml
@model SopalS.Models.ConteneurModel.HistoEtalonnage

@{
    ViewData["Title"] = "Ajouter un HistoEtalonnage";
}
<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/" data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
    <style>
        .navbar-custom {
            background-color: #000080;
        }

            .navbar-custom .nav-link {
                color: #ffffff;
            }

            .navbar-custom .navbar-brand {
                color: #ffffff;
            }

        .content-container {
            margin-top: 20px;
        }
    </style>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700&display=swap" rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="../assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="../assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="../assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="../assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="../assets/vendor/js/helpers.js"></script>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/2.1.2/css/dataTables.dataTables.css" rel="stylesheet" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-custom" data-bs-theme="dark">
            <div class="container-fluid">
                <span class="app-brand-text demo menu-text fw-bolder ms-2">
                    <img src="~/img/logosopal.png" class="img-fluid" style="max-width:50px; height: 50px;" alt="Logo Sopal">
                </span>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="" asp-action="">PlAN DI & CASSE A OUTIL</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Conteneur" asp-action="Index">Données de base</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="" asp-action="">Paramétrage</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <a asp-controller="Utilisateur" asp-action="Register" class="bi bi-person-circle"></a>
                    </form>
                </div>
            </div>
        </nav>
    </header>


<form asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Ref" class="control-label"></label>
        <input asp-for="Ref" class="form-control" readonly />
        <span asp-validation-for="Ref" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Date" class="control-label"></label>
        <input asp-for="Date" class="form-control" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Poids" class="control-label"></label>
        <input asp-for="Poids" class="form-control" />
        <span asp-validation-for="Poids" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Unite" class="control-label"></label>
        <input asp-for="Unite" class="form-control" />
        <span asp-validation-for="Unite" class="text-danger"></span>
    </div>
    <br />
    <br />

    <div class="form-group">
            <button class="btn btn-outline-primary mb-2 d-block"style="background-color: #000080;"> Ajouter</button>
    @*     <input type="submit" value="Ajouter" class="btn btn-primary" /> *@
    </div>
</form>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
</body>
</html>

Views/listeConteneurEchu/Details.cshtml
@* @model IEnumerable<SopalS.Models.ConteneurModel.HistoEtalonnage>

@{
    ViewData["Title"] = "Détails HistoEtalonnage";
}

<h1>Détails HistoEtalonnage pour le Conteneur</h1>

@foreach (var histo in Model)
{
    <form asp-action="Add" method="post">
        <div class="form-group">
            <label asp-for="Ref" class="control-label"></label>
            <input asp-for="Ref" class="form-control" readonly />
        </div>

        <div class="form-group">
            <label asp-for="Date" class="control-label"></label>
            <input asp-for="Date" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Poids" class="control-label"></label>
            <input asp-for="Poids" class="form-control" />
            <span asp-validation-for="Poids" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Unite" class="control-label"></label>
            <input asp-for="Unite" class="form-control" />
            <span asp-validation-for="Unite" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Ajouter" class="btn btn-primary" />
        </div>
    </form>
}

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
} *@
@* @model IEnumerable<SopalS.Models.ConteneurModel.HistoEtalonnage>

@{
    ViewData["Title"] = "Add";
}

<h1>Liste des HistoEtalonnages pour le Conteneur</h1>

@foreach (var histo in Model)
{
    <form asp-action="Add" method="post">
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Réf</label>
            <div class="col-sm-10">
                <input asp-for="@histo.Ref" class="form-control" readonly />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Date</label>
            <div class="col-sm-10">
                <input asp-for="@histo.Date" class="form-control" />
                <span asp-validation-for="@histo.Date" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Poids</label>
            <div class="col-sm-10">
                <input asp-for="@histo.Poids" class="form-control" />
                <span asp-validation-for="@histo.Poids" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Unité</label>
            <div class="col-sm-10">
                <input asp-for="@histo.Unite" class="form-control" />
                <span asp-validation-for="@histo.Unite" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Mettre à jour" class="btn btn-outline-primary" />
        </div>
    </form>
    <hr />
}

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
} *@
@model SopalS.Models.ConteneurModel.HistoEtalonnage

@{
    ViewData["Title"] = "Ajouter un HistoEtalonnage";
}



<form asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Ref" class="control-label"></label>
        <input asp-for="Ref" class="form-control" readonly value="@Model.Ref" />
        <span asp-validation-for="Ref" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Date" class="control-label"></label>
        <input asp-for="Date" class="form-control" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Poids" class="control-label"></label>
        <input asp-for="Poids" class="form-control" />
        <span asp-validation-for="Poids" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Unite" class="control-label"></label>
        <input asp-for="Unite" class="form-control" />
        <span asp-validation-for="Unite" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Ajouter" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/listeConteneurEchu/Index.cshtml
@model IEnumerable<SopalS.Models.ConteneurModel.ConteneurViewModel>

<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/" data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
    <style>
        .navbar-custom {
            background-color: #000080;
        }

            .navbar-custom .nav-link {
                color: #ffffff;
            }

            .navbar-custom .navbar-brand {
                color: #ffffff;
            }

        .content-container {
            margin-top: 20px;
        }
    </style>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700&display=swap" rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="../assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="../assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="../assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="../assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="../assets/vendor/js/helpers.js"></script>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/2.1.2/css/dataTables.dataTables.css" rel="stylesheet" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-custom" data-bs-theme="dark">
            <div class="container-fluid">
                <span class="app-brand-text demo menu-text fw-bolder ms-2">
                    <img src="~/img/logosopal.png" class="img-fluid" style="max-width:50px; height: 50px;" alt="Logo Sopal">
                </span>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="" asp-action="">PlAN DI & CASSE A OUTIL</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Conteneur" asp-action="Index">Données de base</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="listeConteneurEchu" asp-action="Index">Paramétrage</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <a asp-controller="Utilisateur" asp-action="Register" class="bi bi-person-circle"></a>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div class="container content-container">
        <table class="display" id="contid">
            <thead>
                <tr>
                    <th>Réf</th>
                    <th>Code-barres</th>
                    <th>Date Mise En Service</th>
                    <th>Périodicité d'Étalonnage</th>
                    <th>Date Dernier Étalonnage</th>
                    <th>Emplacement ID</th>
                    <th>Date Prochain Étalonnage</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var conteneur in Model)
                {
                    <tr>
                        <td>@conteneur.Ref</td>
                        <td>@conteneur.CodeBarres</td>
                        <td>@conteneur.DateMiseEnService.ToShortDateString()</td>
                        <td>@conteneur.PeriodiciteEtalonnage</td>
                        <td>@(conteneur.DateDernierEtalonnage.HasValue ? conteneur.DateDernierEtalonnage.Value.ToShortDateString() : "N/A")</td>
                        <td>@conteneur.EmplacementId</td>
                        <td>@conteneur.DateProchainEtalonnage.ToShortDateString()</td>
                        <td>
                            <a class="btn btn-outline-primary" asp-controller="listeConteneurEchu" asp-action="Add" asp-route-id="@conteneur.Ref">Valider</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    @section Scripts {
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/2.1.2/js/dataTables.dataTables.js"></script>
        <script>
            $(document).ready(function () {
                $('#contid').DataTable();
            });
        </script>
    }
</body>
</html>